---
name: "Feature Request"
description: "Suggest a new feature or improvement."
title: "[Feature] "
labels: [enhancement]
body:
  - type: textarea
    id: what-feature
    attributes:
      label: "What would you like to see?"
      description: "Describe the feature or improvement you are suggesting."
      placeholder: "A clear and concise description of the feature."
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: "Why is this needed?"
      description: "Explain why this feature would be useful."
      placeholder: "This would help because ..."
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Have you considered any alternatives?"
      placeholder: "Other ways to solve this ..."
    validations:
      required: false
